source "https://rubygems.org"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
gem 'dotenv', groups: [:development, :test]

gem "grpc", "~> 1.80"

gem "discordrb", "~> 3.7"
gem "opus-ruby"

gem "zeitwerk", "~> 2.7"
