// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: discord_jockey.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DiscordJockeyService_Ping_FullMethodName = "/DiscordJockeyService/Ping"
)

// DiscordJockeyServiceClient is the client API for DiscordJockeyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// service definition
type DiscordJockeyServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type discordJockeyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscordJockeyServiceClient(cc grpc.ClientConnInterface) DiscordJockeyServiceClient {
	return &discordJockeyServiceClient{cc}
}

func (c *discordJockeyServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, DiscordJockeyService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscordJockeyServiceServer is the server API for DiscordJockeyService service.
// All implementations must embed UnimplementedDiscordJockeyServiceServer
// for forward compatibility.
//
// service definition
type DiscordJockeyServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedDiscordJockeyServiceServer()
}

// UnimplementedDiscordJockeyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDiscordJockeyServiceServer struct{}

func (UnimplementedDiscordJockeyServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedDiscordJockeyServiceServer) mustEmbedUnimplementedDiscordJockeyServiceServer() {}
func (UnimplementedDiscordJockeyServiceServer) testEmbeddedByValue()                              {}

// UnsafeDiscordJockeyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscordJockeyServiceServer will
// result in compilation errors.
type UnsafeDiscordJockeyServiceServer interface {
	mustEmbedUnimplementedDiscordJockeyServiceServer()
}

func RegisterDiscordJockeyServiceServer(s grpc.ServiceRegistrar, srv DiscordJockeyServiceServer) {
	// If the following call panics, it indicates UnimplementedDiscordJockeyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DiscordJockeyService_ServiceDesc, srv)
}

func _DiscordJockeyService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscordJockeyServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiscordJockeyService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscordJockeyServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiscordJockeyService_ServiceDesc is the grpc.ServiceDesc for DiscordJockeyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiscordJockeyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "DiscordJockeyService",
	HandlerType: (*DiscordJockeyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _DiscordJockeyService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discord_jockey.proto",
}
