// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: radio-jockey.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueRequest) Reset() {
	*x = ListQueueRequest{}
	mi := &file_radio_jockey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueRequest) ProtoMessage() {}

func (x *ListQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueRequest.ProtoReflect.Descriptor instead.
func (*ListQueueRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{0}
}

func (x *ListQueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueResponse) Reset() {
	*x = ListQueueResponse{}
	mi := &file_radio_jockey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueResponse) ProtoMessage() {}

func (x *ListQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueResponse.ProtoReflect.Descriptor instead.
func (*ListQueueResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{1}
}

func (x *ListQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PauseTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     int32                  `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTrackRequest) Reset() {
	*x = PauseTrackRequest{}
	mi := &file_radio_jockey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTrackRequest) ProtoMessage() {}

func (x *PauseTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTrackRequest.ProtoReflect.Descriptor instead.
func (*PauseTrackRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{2}
}

func (x *PauseTrackRequest) GetSessionId() int32 {
	if x != nil {
		return x.SessionId
	}
	return 0
}

type PauseTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseTrackResponse) Reset() {
	*x = PauseTrackResponse{}
	mi := &file_radio_jockey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseTrackResponse) ProtoMessage() {}

func (x *PauseTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseTrackResponse.ProtoReflect.Descriptor instead.
func (*PauseTrackResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{3}
}

func (x *PauseTrackResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AddTrackToQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TrackUrl      string                 `protobuf:"bytes,2,opt,name=track_url,json=trackUrl,proto3" json:"track_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackToQueueRequest) Reset() {
	*x = AddTrackToQueueRequest{}
	mi := &file_radio_jockey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackToQueueRequest) ProtoMessage() {}

func (x *AddTrackToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackToQueueRequest.ProtoReflect.Descriptor instead.
func (*AddTrackToQueueRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{4}
}

func (x *AddTrackToQueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddTrackToQueueRequest) GetTrackUrl() string {
	if x != nil {
		return x.TrackUrl
	}
	return ""
}

type AddTrackToQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackToQueueResponse) Reset() {
	*x = AddTrackToQueueResponse{}
	mi := &file_radio_jockey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackToQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackToQueueResponse) ProtoMessage() {}

func (x *AddTrackToQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackToQueueResponse.ProtoReflect.Descriptor instead.
func (*AddTrackToQueueResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{5}
}

func (x *AddTrackToQueueResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamRequest) Reset() {
	*x = StopStreamRequest{}
	mi := &file_radio_jockey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamRequest) ProtoMessage() {}

func (x *StopStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamRequest.ProtoReflect.Descriptor instead.
func (*StopStreamRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{6}
}

type StopStreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopStreamResponse) Reset() {
	*x = StopStreamResponse{}
	mi := &file_radio_jockey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopStreamResponse) ProtoMessage() {}

func (x *StopStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopStreamResponse.ProtoReflect.Descriptor instead.
func (*StopStreamResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{7}
}

func (x *StopStreamResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_radio_jockey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{8}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_radio_jockey_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_radio_jockey_proto protoreflect.FileDescriptor

const file_radio_jockey_proto_rawDesc = "" +
	"\n" +
	"\x12radio-jockey.proto\"1\n" +
	"\x10ListQueueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"-\n" +
	"\x11ListQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"2\n" +
	"\x11PauseTrackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\x05R\tsessionId\".\n" +
	"\x12PauseTrackResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"T\n" +
	"\x16AddTrackToQueueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttrack_url\x18\x02 \x01(\tR\btrackUrl\"3\n" +
	"\x17AddTrackToQueueResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x13\n" +
	"\x11StopStreamRequest\".\n" +
	"\x12StopStreamResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage25\n" +
	"\fRadioService\x12%\n" +
	"\x04Ping\x12\f.PingRequest\x1a\r.PingResponse\"\x00B\x12Z\x10server/src/protob\x06proto3"

var (
	file_radio_jockey_proto_rawDescOnce sync.Once
	file_radio_jockey_proto_rawDescData []byte
)

func file_radio_jockey_proto_rawDescGZIP() []byte {
	file_radio_jockey_proto_rawDescOnce.Do(func() {
		file_radio_jockey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_radio_jockey_proto_rawDesc), len(file_radio_jockey_proto_rawDesc)))
	})
	return file_radio_jockey_proto_rawDescData
}

var file_radio_jockey_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_radio_jockey_proto_goTypes = []any{
	(*ListQueueRequest)(nil),        // 0: ListQueueRequest
	(*ListQueueResponse)(nil),       // 1: ListQueueResponse
	(*PauseTrackRequest)(nil),       // 2: PauseTrackRequest
	(*PauseTrackResponse)(nil),      // 3: PauseTrackResponse
	(*AddTrackToQueueRequest)(nil),  // 4: AddTrackToQueueRequest
	(*AddTrackToQueueResponse)(nil), // 5: AddTrackToQueueResponse
	(*StopStreamRequest)(nil),       // 6: StopStreamRequest
	(*StopStreamResponse)(nil),      // 7: StopStreamResponse
	(*PingRequest)(nil),             // 8: PingRequest
	(*PingResponse)(nil),            // 9: PingResponse
}
var file_radio_jockey_proto_depIdxs = []int32{
	8, // 0: RadioService.Ping:input_type -> PingRequest
	9, // 1: RadioService.Ping:output_type -> PingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_radio_jockey_proto_init() }
func file_radio_jockey_proto_init() {
	if File_radio_jockey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_radio_jockey_proto_rawDesc), len(file_radio_jockey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_radio_jockey_proto_goTypes,
		DependencyIndexes: file_radio_jockey_proto_depIdxs,
		MessageInfos:      file_radio_jockey_proto_msgTypes,
	}.Build()
	File_radio_jockey_proto = out.File
	file_radio_jockey_proto_goTypes = nil
	file_radio_jockey_proto_depIdxs = nil
}
