// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: radio-jockey.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_radio_jockey_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{0}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_radio_jockey_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_radio_jockey_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_radio_jockey_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{3}
}

func (x *CreateSessionResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_radio_jockey_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{4}
}

func (x *GetSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamUrl     string                 `protobuf:"bytes,1,opt,name=stream_url,json=streamUrl,proto3" json:"stream_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_radio_jockey_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{5}
}

func (x *GetSessionResponse) GetStreamUrl() string {
	if x != nil {
		return x.StreamUrl
	}
	return ""
}

type RequestNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNonceRequest) Reset() {
	*x = RequestNonceRequest{}
	mi := &file_radio_jockey_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNonceRequest) ProtoMessage() {}

func (x *RequestNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNonceRequest.ProtoReflect.Descriptor instead.
func (*RequestNonceRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{6}
}

type RequestNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         string                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestNonceResponse) Reset() {
	*x = RequestNonceResponse{}
	mi := &file_radio_jockey_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestNonceResponse) ProtoMessage() {}

func (x *RequestNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestNonceResponse.ProtoReflect.Descriptor instead.
func (*RequestNonceResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{7}
}

func (x *RequestNonceResponse) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

type RespondNonceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PassKey       string                 `protobuf:"bytes,1,opt,name=pass_key,json=passKey,proto3" json:"pass_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondNonceRequest) Reset() {
	*x = RespondNonceRequest{}
	mi := &file_radio_jockey_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondNonceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondNonceRequest) ProtoMessage() {}

func (x *RespondNonceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondNonceRequest.ProtoReflect.Descriptor instead.
func (*RespondNonceRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{8}
}

func (x *RespondNonceRequest) GetPassKey() string {
	if x != nil {
		return x.PassKey
	}
	return ""
}

type RespondNonceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthToken     string                 `protobuf:"bytes,1,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespondNonceResponse) Reset() {
	*x = RespondNonceResponse{}
	mi := &file_radio_jockey_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespondNonceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespondNonceResponse) ProtoMessage() {}

func (x *RespondNonceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespondNonceResponse.ProtoReflect.Descriptor instead.
func (*RespondNonceResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{9}
}

func (x *RespondNonceResponse) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type DeleteSessionAuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionAuthRequest) Reset() {
	*x = DeleteSessionAuthRequest{}
	mi := &file_radio_jockey_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionAuthRequest) ProtoMessage() {}

func (x *DeleteSessionAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionAuthRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionAuthRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteSessionAuthRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type DeleteSessionAuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionAuthResponse) Reset() {
	*x = DeleteSessionAuthResponse{}
	mi := &file_radio_jockey_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionAuthResponse) ProtoMessage() {}

func (x *DeleteSessionAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionAuthResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionAuthResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{11}
}

type AddTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TrackUrl      string                 `protobuf:"bytes,2,opt,name=track_url,json=trackUrl,proto3" json:"track_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackRequest) Reset() {
	*x = AddTrackRequest{}
	mi := &file_radio_jockey_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackRequest) ProtoMessage() {}

func (x *AddTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackRequest.ProtoReflect.Descriptor instead.
func (*AddTrackRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{12}
}

func (x *AddTrackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AddTrackRequest) GetTrackUrl() string {
	if x != nil {
		return x.TrackUrl
	}
	return ""
}

type AddTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Track         *Track                 `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddTrackResponse) Reset() {
	*x = AddTrackResponse{}
	mi := &file_radio_jockey_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrackResponse) ProtoMessage() {}

func (x *AddTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrackResponse.ProtoReflect.Descriptor instead.
func (*AddTrackResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{13}
}

func (x *AddTrackResponse) GetTrack() *Track {
	if x != nil {
		return x.Track
	}
	return nil
}

type RemoveTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Index         uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrackRequest) Reset() {
	*x = RemoveTrackRequest{}
	mi := &file_radio_jockey_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrackRequest) ProtoMessage() {}

func (x *RemoveTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrackRequest.ProtoReflect.Descriptor instead.
func (*RemoveTrackRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveTrackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RemoveTrackRequest) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type RemoveTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveTrackResponse) Reset() {
	*x = RemoveTrackResponse{}
	mi := &file_radio_jockey_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveTrackResponse) ProtoMessage() {}

func (x *RemoveTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveTrackResponse.ProtoReflect.Descriptor instead.
func (*RemoveTrackResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{15}
}

type SkipTrackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipTrackRequest) Reset() {
	*x = SkipTrackRequest{}
	mi := &file_radio_jockey_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipTrackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipTrackRequest) ProtoMessage() {}

func (x *SkipTrackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipTrackRequest.ProtoReflect.Descriptor instead.
func (*SkipTrackRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{16}
}

func (x *SkipTrackRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SkipTrackResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkipTrackResponse) Reset() {
	*x = SkipTrackResponse{}
	mi := &file_radio_jockey_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkipTrackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkipTrackResponse) ProtoMessage() {}

func (x *SkipTrackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkipTrackResponse.ProtoReflect.Descriptor instead.
func (*SkipTrackResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{17}
}

type ListQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueRequest) Reset() {
	*x = ListQueueRequest{}
	mi := &file_radio_jockey_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueRequest) ProtoMessage() {}

func (x *ListQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueRequest.ProtoReflect.Descriptor instead.
func (*ListQueueRequest) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{18}
}

func (x *ListQueueRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ListQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tracks        []*Track               `protobuf:"bytes,1,rep,name=tracks,proto3" json:"tracks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueResponse) Reset() {
	*x = ListQueueResponse{}
	mi := &file_radio_jockey_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueResponse) ProtoMessage() {}

func (x *ListQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueResponse.ProtoReflect.Descriptor instead.
func (*ListQueueResponse) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{19}
}

func (x *ListQueueResponse) GetTracks() []*Track {
	if x != nil {
		return x.Tracks
	}
	return nil
}

type Track struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	SourceId      string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	Artist        string                 `protobuf:"bytes,5,opt,name=artist,proto3" json:"artist,omitempty"`
	Duration      int64                  `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Track) Reset() {
	*x = Track{}
	mi := &file_radio_jockey_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Track) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Track) ProtoMessage() {}

func (x *Track) ProtoReflect() protoreflect.Message {
	mi := &file_radio_jockey_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Track.ProtoReflect.Descriptor instead.
func (*Track) Descriptor() ([]byte, []int) {
	return file_radio_jockey_proto_rawDescGZIP(), []int{20}
}

func (x *Track) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Track) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Track) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *Track) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Track) GetArtist() string {
	if x != nil {
		return x.Artist
	}
	return ""
}

func (x *Track) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

var File_radio_jockey_proto protoreflect.FileDescriptor

const file_radio_jockey_proto_rawDesc = "" +
	"\n" +
	"\x12radio-jockey.proto\"\r\n" +
	"\vPingRequest\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"5\n" +
	"\x14CreateSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"6\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\"2\n" +
	"\x11GetSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x12GetSessionResponse\x12\x1d\n" +
	"\n" +
	"stream_url\x18\x01 \x01(\tR\tstreamUrl\"\x15\n" +
	"\x13RequestNonceRequest\",\n" +
	"\x14RequestNonceResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\tR\x05nonce\"0\n" +
	"\x13RespondNonceRequest\x12\x19\n" +
	"\bpass_key\x18\x01 \x01(\tR\apassKey\"5\n" +
	"\x14RespondNonceResponse\x12\x1d\n" +
	"\n" +
	"auth_token\x18\x01 \x01(\tR\tauthToken\"9\n" +
	"\x18DeleteSessionAuthRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x1b\n" +
	"\x19DeleteSessionAuthResponse\"M\n" +
	"\x0fAddTrackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttrack_url\x18\x02 \x01(\tR\btrackUrl\"0\n" +
	"\x10AddTrackResponse\x12\x1c\n" +
	"\x05track\x18\x01 \x01(\v2\x06.TrackR\x05track\"I\n" +
	"\x12RemoveTrackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\"\x15\n" +
	"\x13RemoveTrackResponse\"1\n" +
	"\x10SkipTrackRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x13\n" +
	"\x11SkipTrackResponse\"1\n" +
	"\x10ListQueueRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"3\n" +
	"\x11ListQueueResponse\x12\x1e\n" +
	"\x06tracks\x18\x01 \x03(\v2\x06.TrackR\x06tracks\"\x96\x01\n" +
	"\x05Track\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x16\n" +
	"\x06artist\x18\x05 \x01(\tR\x06artist\x12\x1a\n" +
	"\bduration\x18\x06 \x01(\x03R\bduration2\xd7\x04\n" +
	"\fRadioService\x12%\n" +
	"\x04Ping\x12\f.PingRequest\x1a\r.PingResponse\"\x00\x12=\n" +
	"\fRequestNonce\x12\x14.RequestNonceRequest\x1a\x15.RequestNonceResponse\"\x00\x12=\n" +
	"\fRespondNonce\x12\x14.RespondNonceRequest\x1a\x15.RespondNonceResponse\"\x00\x12@\n" +
	"\rCreateSession\x12\x15.CreateSessionRequest\x1a\x16.CreateSessionResponse\"\x00\x127\n" +
	"\n" +
	"GetSession\x12\x12.GetSessionRequest\x1a\x13.GetSessionResponse\"\x00\x12L\n" +
	"\x11DeleteSessionAuth\x12\x19.DeleteSessionAuthRequest\x1a\x1a.DeleteSessionAuthResponse\"\x00\x121\n" +
	"\bAddTrack\x12\x10.AddTrackRequest\x1a\x11.AddTrackResponse\"\x00\x12:\n" +
	"\vRemoveTrack\x12\x13.RemoveTrackRequest\x1a\x14.RemoveTrackResponse\"\x00\x124\n" +
	"\tSkipTrack\x12\x11.SkipTrackRequest\x1a\x12.SkipTrackResponse\"\x00\x124\n" +
	"\tListQueue\x12\x11.ListQueueRequest\x1a\x12.ListQueueResponse\"\x00B\x12Z\x10server/src/protob\x06proto3"

var (
	file_radio_jockey_proto_rawDescOnce sync.Once
	file_radio_jockey_proto_rawDescData []byte
)

func file_radio_jockey_proto_rawDescGZIP() []byte {
	file_radio_jockey_proto_rawDescOnce.Do(func() {
		file_radio_jockey_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_radio_jockey_proto_rawDesc), len(file_radio_jockey_proto_rawDesc)))
	})
	return file_radio_jockey_proto_rawDescData
}

var file_radio_jockey_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_radio_jockey_proto_goTypes = []any{
	(*PingRequest)(nil),               // 0: PingRequest
	(*PingResponse)(nil),              // 1: PingResponse
	(*CreateSessionRequest)(nil),      // 2: CreateSessionRequest
	(*CreateSessionResponse)(nil),     // 3: CreateSessionResponse
	(*GetSessionRequest)(nil),         // 4: GetSessionRequest
	(*GetSessionResponse)(nil),        // 5: GetSessionResponse
	(*RequestNonceRequest)(nil),       // 6: RequestNonceRequest
	(*RequestNonceResponse)(nil),      // 7: RequestNonceResponse
	(*RespondNonceRequest)(nil),       // 8: RespondNonceRequest
	(*RespondNonceResponse)(nil),      // 9: RespondNonceResponse
	(*DeleteSessionAuthRequest)(nil),  // 10: DeleteSessionAuthRequest
	(*DeleteSessionAuthResponse)(nil), // 11: DeleteSessionAuthResponse
	(*AddTrackRequest)(nil),           // 12: AddTrackRequest
	(*AddTrackResponse)(nil),          // 13: AddTrackResponse
	(*RemoveTrackRequest)(nil),        // 14: RemoveTrackRequest
	(*RemoveTrackResponse)(nil),       // 15: RemoveTrackResponse
	(*SkipTrackRequest)(nil),          // 16: SkipTrackRequest
	(*SkipTrackResponse)(nil),         // 17: SkipTrackResponse
	(*ListQueueRequest)(nil),          // 18: ListQueueRequest
	(*ListQueueResponse)(nil),         // 19: ListQueueResponse
	(*Track)(nil),                     // 20: Track
}
var file_radio_jockey_proto_depIdxs = []int32{
	20, // 0: AddTrackResponse.track:type_name -> Track
	20, // 1: ListQueueResponse.tracks:type_name -> Track
	0,  // 2: RadioService.Ping:input_type -> PingRequest
	6,  // 3: RadioService.RequestNonce:input_type -> RequestNonceRequest
	8,  // 4: RadioService.RespondNonce:input_type -> RespondNonceRequest
	2,  // 5: RadioService.CreateSession:input_type -> CreateSessionRequest
	4,  // 6: RadioService.GetSession:input_type -> GetSessionRequest
	10, // 7: RadioService.DeleteSessionAuth:input_type -> DeleteSessionAuthRequest
	12, // 8: RadioService.AddTrack:input_type -> AddTrackRequest
	14, // 9: RadioService.RemoveTrack:input_type -> RemoveTrackRequest
	16, // 10: RadioService.SkipTrack:input_type -> SkipTrackRequest
	18, // 11: RadioService.ListQueue:input_type -> ListQueueRequest
	1,  // 12: RadioService.Ping:output_type -> PingResponse
	7,  // 13: RadioService.RequestNonce:output_type -> RequestNonceResponse
	9,  // 14: RadioService.RespondNonce:output_type -> RespondNonceResponse
	3,  // 15: RadioService.CreateSession:output_type -> CreateSessionResponse
	5,  // 16: RadioService.GetSession:output_type -> GetSessionResponse
	11, // 17: RadioService.DeleteSessionAuth:output_type -> DeleteSessionAuthResponse
	13, // 18: RadioService.AddTrack:output_type -> AddTrackResponse
	15, // 19: RadioService.RemoveTrack:output_type -> RemoveTrackResponse
	17, // 20: RadioService.SkipTrack:output_type -> SkipTrackResponse
	19, // 21: RadioService.ListQueue:output_type -> ListQueueResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_radio_jockey_proto_init() }
func file_radio_jockey_proto_init() {
	if File_radio_jockey_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_radio_jockey_proto_rawDesc), len(file_radio_jockey_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_radio_jockey_proto_goTypes,
		DependencyIndexes: file_radio_jockey_proto_depIdxs,
		MessageInfos:      file_radio_jockey_proto_msgTypes,
	}.Build()
	File_radio_jockey_proto = out.File
	file_radio_jockey_proto_goTypes = nil
	file_radio_jockey_proto_depIdxs = nil
}
