# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: discord_jockey.proto

require 'google/protobuf'


descriptor_data = "\n\x14\x64iscord_jockey.proto\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x14\x44iscordJockeyService\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x42\x12Z\x10server/src/protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingResponse").msgclass
