# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: discord_jockey.proto for package ''

require 'grpc'
require 'discord_jockey_pb'

module DiscordJockeyService
  # service definition
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'DiscordJockeyService'

    rpc :Ping, ::PingRequest, ::PingResponse
  end

  Stub = Service.rpc_stub_class
end
