# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: radio.proto

require 'google/protobuf'


descriptor_data = "\n\x0bradio.proto\"&\n\x10ListQueueRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\"$\n\x11ListQueueResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\'\n\x11PauseTrackRequest\x12\x12\n\nsession_id\x18\x01 \x01(\x05\"%\n\x12PauseTrackResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"?\n\x16\x41\x64\x64TrackToQueueRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\ttrack_url\x18\x02 \x01(\t\"*\n\x17\x41\x64\x64TrackToQueueResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x13\n\x11StopStreamRequest\"%\n\x12StopStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\r\n\x0bPingRequest\"\x1f\n\x0cPingResponse\x12\x0f\n\x07message\x18\x01 \x01(\t25\n\x0cRadioService\x12%\n\x04Ping\x12\x0c.PingRequest\x1a\r.PingResponse\"\x00\x42\x12Z\x10server/src/protob\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

ListQueueRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ListQueueRequest").msgclass
ListQueueResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("ListQueueResponse").msgclass
PauseTrackRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PauseTrackRequest").msgclass
PauseTrackResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PauseTrackResponse").msgclass
AddTrackToQueueRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddTrackToQueueRequest").msgclass
AddTrackToQueueResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddTrackToQueueResponse").msgclass
StopStreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StopStreamRequest").msgclass
StopStreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("StopStreamResponse").msgclass
PingRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingRequest").msgclass
PingResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("PingResponse").msgclass
