// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file radio-jockey.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddTrackRequest, AddTrackResponse, CreateSessionRequest, CreateSessionResponse, ListQueueRequest, ListQueueResponse, PingRequest, PingResponse, RemoveTrackRequest, RemoveTrackResponse, SkipTrackRequest, SkipTrackResponse } from "./radio-jockey_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service RadioService
 */
export const RadioService = {
  typeName: "RadioService",
  methods: {
    /**
     * @generated from rpc RadioService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RadioService.CreateSession
     */
    createSession: {
      name: "CreateSession",
      I: CreateSessionRequest,
      O: CreateSessionResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RadioService.AddTrack
     */
    addTrack: {
      name: "AddTrack",
      I: AddTrackRequest,
      O: AddTrackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RadioService.RemoveTrack
     */
    removeTrack: {
      name: "RemoveTrack",
      I: RemoveTrackRequest,
      O: RemoveTrackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RadioService.SkipTrack
     */
    skipTrack: {
      name: "SkipTrack",
      I: SkipTrackRequest,
      O: SkipTrackResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc RadioService.ListQueue
     */
    listQueue: {
      name: "ListQueue",
      I: ListQueueRequest,
      O: ListQueueResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

