// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: radio.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	proto "server/src/proto"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RadioServiceName is the fully-qualified name of the RadioService service.
	RadioServiceName = "RadioService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RadioServicePingProcedure is the fully-qualified name of the RadioService's Ping RPC.
	RadioServicePingProcedure = "/RadioService/Ping"
)

// RadioServiceClient is a client for the RadioService service.
type RadioServiceClient interface {
	Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error)
}

// NewRadioServiceClient constructs a client for the RadioService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRadioServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RadioServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	radioServiceMethods := proto.File_radio_proto.Services().ByName("RadioService").Methods()
	return &radioServiceClient{
		ping: connect.NewClient[proto.PingRequest, proto.PingResponse](
			httpClient,
			baseURL+RadioServicePingProcedure,
			connect.WithSchema(radioServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
	}
}

// radioServiceClient implements RadioServiceClient.
type radioServiceClient struct {
	ping *connect.Client[proto.PingRequest, proto.PingResponse]
}

// Ping calls RadioService.Ping.
func (c *radioServiceClient) Ping(ctx context.Context, req *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// RadioServiceHandler is an implementation of the RadioService service.
type RadioServiceHandler interface {
	Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error)
}

// NewRadioServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRadioServiceHandler(svc RadioServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	radioServiceMethods := proto.File_radio_proto.Services().ByName("RadioService").Methods()
	radioServicePingHandler := connect.NewUnaryHandler(
		RadioServicePingProcedure,
		svc.Ping,
		connect.WithSchema(radioServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	return "/RadioService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RadioServicePingProcedure:
			radioServicePingHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRadioServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRadioServiceHandler struct{}

func (UnimplementedRadioServiceHandler) Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.Ping is not implemented"))
}
