// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: radio-jockey.proto

package protoconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	proto "server/src/proto"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RadioServiceName is the fully-qualified name of the RadioService service.
	RadioServiceName = "RadioService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RadioServicePingProcedure is the fully-qualified name of the RadioService's Ping RPC.
	RadioServicePingProcedure = "/RadioService/Ping"
	// RadioServiceRequestNonceProcedure is the fully-qualified name of the RadioService's RequestNonce
	// RPC.
	RadioServiceRequestNonceProcedure = "/RadioService/RequestNonce"
	// RadioServiceRespondNonceProcedure is the fully-qualified name of the RadioService's RespondNonce
	// RPC.
	RadioServiceRespondNonceProcedure = "/RadioService/RespondNonce"
	// RadioServiceCreateSessionProcedure is the fully-qualified name of the RadioService's
	// CreateSession RPC.
	RadioServiceCreateSessionProcedure = "/RadioService/CreateSession"
	// RadioServiceGetSessionProcedure is the fully-qualified name of the RadioService's GetSession RPC.
	RadioServiceGetSessionProcedure = "/RadioService/GetSession"
	// RadioServiceDeleteSessionAuthProcedure is the fully-qualified name of the RadioService's
	// DeleteSessionAuth RPC.
	RadioServiceDeleteSessionAuthProcedure = "/RadioService/DeleteSessionAuth"
	// RadioServiceAddTrackProcedure is the fully-qualified name of the RadioService's AddTrack RPC.
	RadioServiceAddTrackProcedure = "/RadioService/AddTrack"
	// RadioServiceRemoveTrackProcedure is the fully-qualified name of the RadioService's RemoveTrack
	// RPC.
	RadioServiceRemoveTrackProcedure = "/RadioService/RemoveTrack"
	// RadioServiceSkipTrackProcedure is the fully-qualified name of the RadioService's SkipTrack RPC.
	RadioServiceSkipTrackProcedure = "/RadioService/SkipTrack"
	// RadioServiceListQueueProcedure is the fully-qualified name of the RadioService's ListQueue RPC.
	RadioServiceListQueueProcedure = "/RadioService/ListQueue"
	// RadioServiceListSessionsProcedure is the fully-qualified name of the RadioService's ListSessions
	// RPC.
	RadioServiceListSessionsProcedure = "/RadioService/ListSessions"
	// RadioServiceListSessionArchivesProcedure is the fully-qualified name of the RadioService's
	// ListSessionArchives RPC.
	RadioServiceListSessionArchivesProcedure = "/RadioService/ListSessionArchives"
	// RadioServiceGetSessionArchiveProcedure is the fully-qualified name of the RadioService's
	// GetSessionArchive RPC.
	RadioServiceGetSessionArchiveProcedure = "/RadioService/GetSessionArchive"
	// RadioServiceDeleteSessionArchiveProcedure is the fully-qualified name of the RadioService's
	// DeleteSessionArchive RPC.
	RadioServiceDeleteSessionArchiveProcedure = "/RadioService/DeleteSessionArchive"
)

// RadioServiceClient is a client for the RadioService service.
type RadioServiceClient interface {
	Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error)
	RequestNonce(context.Context, *connect.Request[proto.RequestNonceRequest]) (*connect.Response[proto.RequestNonceResponse], error)
	RespondNonce(context.Context, *connect.Request[proto.RespondNonceRequest]) (*connect.Response[proto.RespondNonceResponse], error)
	CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.CreateSessionResponse], error)
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.GetSessionResponse], error)
	DeleteSessionAuth(context.Context, *connect.Request[proto.DeleteSessionAuthRequest]) (*connect.Response[proto.DeleteSessionAuthResponse], error)
	AddTrack(context.Context, *connect.Request[proto.AddTrackRequest]) (*connect.Response[proto.AddTrackResponse], error)
	RemoveTrack(context.Context, *connect.Request[proto.RemoveTrackRequest]) (*connect.Response[proto.RemoveTrackResponse], error)
	SkipTrack(context.Context, *connect.Request[proto.SkipTrackRequest]) (*connect.Response[proto.SkipTrackResponse], error)
	ListQueue(context.Context, *connect.Request[proto.ListQueueRequest]) (*connect.Response[proto.ListQueueResponse], error)
	ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error)
	ListSessionArchives(context.Context, *connect.Request[proto.ListSessionArchivesRequest]) (*connect.Response[proto.ListSessionArchivesResponse], error)
	GetSessionArchive(context.Context, *connect.Request[proto.GetSessionArchiveRequest]) (*connect.Response[proto.GetSessionArchiveResponse], error)
	DeleteSessionArchive(context.Context, *connect.Request[proto.DeleteSessionArchiveRequest]) (*connect.Response[proto.DeleteSessionArchiveResponse], error)
}

// NewRadioServiceClient constructs a client for the RadioService service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRadioServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RadioServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	radioServiceMethods := proto.File_radio_jockey_proto.Services().ByName("RadioService").Methods()
	return &radioServiceClient{
		ping: connect.NewClient[proto.PingRequest, proto.PingResponse](
			httpClient,
			baseURL+RadioServicePingProcedure,
			connect.WithSchema(radioServiceMethods.ByName("Ping")),
			connect.WithClientOptions(opts...),
		),
		requestNonce: connect.NewClient[proto.RequestNonceRequest, proto.RequestNonceResponse](
			httpClient,
			baseURL+RadioServiceRequestNonceProcedure,
			connect.WithSchema(radioServiceMethods.ByName("RequestNonce")),
			connect.WithClientOptions(opts...),
		),
		respondNonce: connect.NewClient[proto.RespondNonceRequest, proto.RespondNonceResponse](
			httpClient,
			baseURL+RadioServiceRespondNonceProcedure,
			connect.WithSchema(radioServiceMethods.ByName("RespondNonce")),
			connect.WithClientOptions(opts...),
		),
		createSession: connect.NewClient[proto.CreateSessionRequest, proto.CreateSessionResponse](
			httpClient,
			baseURL+RadioServiceCreateSessionProcedure,
			connect.WithSchema(radioServiceMethods.ByName("CreateSession")),
			connect.WithClientOptions(opts...),
		),
		getSession: connect.NewClient[proto.GetSessionRequest, proto.GetSessionResponse](
			httpClient,
			baseURL+RadioServiceGetSessionProcedure,
			connect.WithSchema(radioServiceMethods.ByName("GetSession")),
			connect.WithClientOptions(opts...),
		),
		deleteSessionAuth: connect.NewClient[proto.DeleteSessionAuthRequest, proto.DeleteSessionAuthResponse](
			httpClient,
			baseURL+RadioServiceDeleteSessionAuthProcedure,
			connect.WithSchema(radioServiceMethods.ByName("DeleteSessionAuth")),
			connect.WithClientOptions(opts...),
		),
		addTrack: connect.NewClient[proto.AddTrackRequest, proto.AddTrackResponse](
			httpClient,
			baseURL+RadioServiceAddTrackProcedure,
			connect.WithSchema(radioServiceMethods.ByName("AddTrack")),
			connect.WithClientOptions(opts...),
		),
		removeTrack: connect.NewClient[proto.RemoveTrackRequest, proto.RemoveTrackResponse](
			httpClient,
			baseURL+RadioServiceRemoveTrackProcedure,
			connect.WithSchema(radioServiceMethods.ByName("RemoveTrack")),
			connect.WithClientOptions(opts...),
		),
		skipTrack: connect.NewClient[proto.SkipTrackRequest, proto.SkipTrackResponse](
			httpClient,
			baseURL+RadioServiceSkipTrackProcedure,
			connect.WithSchema(radioServiceMethods.ByName("SkipTrack")),
			connect.WithClientOptions(opts...),
		),
		listQueue: connect.NewClient[proto.ListQueueRequest, proto.ListQueueResponse](
			httpClient,
			baseURL+RadioServiceListQueueProcedure,
			connect.WithSchema(radioServiceMethods.ByName("ListQueue")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[proto.ListSessionsRequest, proto.ListSessionsResponse](
			httpClient,
			baseURL+RadioServiceListSessionsProcedure,
			connect.WithSchema(radioServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		listSessionArchives: connect.NewClient[proto.ListSessionArchivesRequest, proto.ListSessionArchivesResponse](
			httpClient,
			baseURL+RadioServiceListSessionArchivesProcedure,
			connect.WithSchema(radioServiceMethods.ByName("ListSessionArchives")),
			connect.WithClientOptions(opts...),
		),
		getSessionArchive: connect.NewClient[proto.GetSessionArchiveRequest, proto.GetSessionArchiveResponse](
			httpClient,
			baseURL+RadioServiceGetSessionArchiveProcedure,
			connect.WithSchema(radioServiceMethods.ByName("GetSessionArchive")),
			connect.WithClientOptions(opts...),
		),
		deleteSessionArchive: connect.NewClient[proto.DeleteSessionArchiveRequest, proto.DeleteSessionArchiveResponse](
			httpClient,
			baseURL+RadioServiceDeleteSessionArchiveProcedure,
			connect.WithSchema(radioServiceMethods.ByName("DeleteSessionArchive")),
			connect.WithClientOptions(opts...),
		),
	}
}

// radioServiceClient implements RadioServiceClient.
type radioServiceClient struct {
	ping                 *connect.Client[proto.PingRequest, proto.PingResponse]
	requestNonce         *connect.Client[proto.RequestNonceRequest, proto.RequestNonceResponse]
	respondNonce         *connect.Client[proto.RespondNonceRequest, proto.RespondNonceResponse]
	createSession        *connect.Client[proto.CreateSessionRequest, proto.CreateSessionResponse]
	getSession           *connect.Client[proto.GetSessionRequest, proto.GetSessionResponse]
	deleteSessionAuth    *connect.Client[proto.DeleteSessionAuthRequest, proto.DeleteSessionAuthResponse]
	addTrack             *connect.Client[proto.AddTrackRequest, proto.AddTrackResponse]
	removeTrack          *connect.Client[proto.RemoveTrackRequest, proto.RemoveTrackResponse]
	skipTrack            *connect.Client[proto.SkipTrackRequest, proto.SkipTrackResponse]
	listQueue            *connect.Client[proto.ListQueueRequest, proto.ListQueueResponse]
	listSessions         *connect.Client[proto.ListSessionsRequest, proto.ListSessionsResponse]
	listSessionArchives  *connect.Client[proto.ListSessionArchivesRequest, proto.ListSessionArchivesResponse]
	getSessionArchive    *connect.Client[proto.GetSessionArchiveRequest, proto.GetSessionArchiveResponse]
	deleteSessionArchive *connect.Client[proto.DeleteSessionArchiveRequest, proto.DeleteSessionArchiveResponse]
}

// Ping calls RadioService.Ping.
func (c *radioServiceClient) Ping(ctx context.Context, req *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// RequestNonce calls RadioService.RequestNonce.
func (c *radioServiceClient) RequestNonce(ctx context.Context, req *connect.Request[proto.RequestNonceRequest]) (*connect.Response[proto.RequestNonceResponse], error) {
	return c.requestNonce.CallUnary(ctx, req)
}

// RespondNonce calls RadioService.RespondNonce.
func (c *radioServiceClient) RespondNonce(ctx context.Context, req *connect.Request[proto.RespondNonceRequest]) (*connect.Response[proto.RespondNonceResponse], error) {
	return c.respondNonce.CallUnary(ctx, req)
}

// CreateSession calls RadioService.CreateSession.
func (c *radioServiceClient) CreateSession(ctx context.Context, req *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.CreateSessionResponse], error) {
	return c.createSession.CallUnary(ctx, req)
}

// GetSession calls RadioService.GetSession.
func (c *radioServiceClient) GetSession(ctx context.Context, req *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.GetSessionResponse], error) {
	return c.getSession.CallUnary(ctx, req)
}

// DeleteSessionAuth calls RadioService.DeleteSessionAuth.
func (c *radioServiceClient) DeleteSessionAuth(ctx context.Context, req *connect.Request[proto.DeleteSessionAuthRequest]) (*connect.Response[proto.DeleteSessionAuthResponse], error) {
	return c.deleteSessionAuth.CallUnary(ctx, req)
}

// AddTrack calls RadioService.AddTrack.
func (c *radioServiceClient) AddTrack(ctx context.Context, req *connect.Request[proto.AddTrackRequest]) (*connect.Response[proto.AddTrackResponse], error) {
	return c.addTrack.CallUnary(ctx, req)
}

// RemoveTrack calls RadioService.RemoveTrack.
func (c *radioServiceClient) RemoveTrack(ctx context.Context, req *connect.Request[proto.RemoveTrackRequest]) (*connect.Response[proto.RemoveTrackResponse], error) {
	return c.removeTrack.CallUnary(ctx, req)
}

// SkipTrack calls RadioService.SkipTrack.
func (c *radioServiceClient) SkipTrack(ctx context.Context, req *connect.Request[proto.SkipTrackRequest]) (*connect.Response[proto.SkipTrackResponse], error) {
	return c.skipTrack.CallUnary(ctx, req)
}

// ListQueue calls RadioService.ListQueue.
func (c *radioServiceClient) ListQueue(ctx context.Context, req *connect.Request[proto.ListQueueRequest]) (*connect.Response[proto.ListQueueResponse], error) {
	return c.listQueue.CallUnary(ctx, req)
}

// ListSessions calls RadioService.ListSessions.
func (c *radioServiceClient) ListSessions(ctx context.Context, req *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// ListSessionArchives calls RadioService.ListSessionArchives.
func (c *radioServiceClient) ListSessionArchives(ctx context.Context, req *connect.Request[proto.ListSessionArchivesRequest]) (*connect.Response[proto.ListSessionArchivesResponse], error) {
	return c.listSessionArchives.CallUnary(ctx, req)
}

// GetSessionArchive calls RadioService.GetSessionArchive.
func (c *radioServiceClient) GetSessionArchive(ctx context.Context, req *connect.Request[proto.GetSessionArchiveRequest]) (*connect.Response[proto.GetSessionArchiveResponse], error) {
	return c.getSessionArchive.CallUnary(ctx, req)
}

// DeleteSessionArchive calls RadioService.DeleteSessionArchive.
func (c *radioServiceClient) DeleteSessionArchive(ctx context.Context, req *connect.Request[proto.DeleteSessionArchiveRequest]) (*connect.Response[proto.DeleteSessionArchiveResponse], error) {
	return c.deleteSessionArchive.CallUnary(ctx, req)
}

// RadioServiceHandler is an implementation of the RadioService service.
type RadioServiceHandler interface {
	Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error)
	RequestNonce(context.Context, *connect.Request[proto.RequestNonceRequest]) (*connect.Response[proto.RequestNonceResponse], error)
	RespondNonce(context.Context, *connect.Request[proto.RespondNonceRequest]) (*connect.Response[proto.RespondNonceResponse], error)
	CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.CreateSessionResponse], error)
	GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.GetSessionResponse], error)
	DeleteSessionAuth(context.Context, *connect.Request[proto.DeleteSessionAuthRequest]) (*connect.Response[proto.DeleteSessionAuthResponse], error)
	AddTrack(context.Context, *connect.Request[proto.AddTrackRequest]) (*connect.Response[proto.AddTrackResponse], error)
	RemoveTrack(context.Context, *connect.Request[proto.RemoveTrackRequest]) (*connect.Response[proto.RemoveTrackResponse], error)
	SkipTrack(context.Context, *connect.Request[proto.SkipTrackRequest]) (*connect.Response[proto.SkipTrackResponse], error)
	ListQueue(context.Context, *connect.Request[proto.ListQueueRequest]) (*connect.Response[proto.ListQueueResponse], error)
	ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error)
	ListSessionArchives(context.Context, *connect.Request[proto.ListSessionArchivesRequest]) (*connect.Response[proto.ListSessionArchivesResponse], error)
	GetSessionArchive(context.Context, *connect.Request[proto.GetSessionArchiveRequest]) (*connect.Response[proto.GetSessionArchiveResponse], error)
	DeleteSessionArchive(context.Context, *connect.Request[proto.DeleteSessionArchiveRequest]) (*connect.Response[proto.DeleteSessionArchiveResponse], error)
}

// NewRadioServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRadioServiceHandler(svc RadioServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	radioServiceMethods := proto.File_radio_jockey_proto.Services().ByName("RadioService").Methods()
	radioServicePingHandler := connect.NewUnaryHandler(
		RadioServicePingProcedure,
		svc.Ping,
		connect.WithSchema(radioServiceMethods.ByName("Ping")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceRequestNonceHandler := connect.NewUnaryHandler(
		RadioServiceRequestNonceProcedure,
		svc.RequestNonce,
		connect.WithSchema(radioServiceMethods.ByName("RequestNonce")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceRespondNonceHandler := connect.NewUnaryHandler(
		RadioServiceRespondNonceProcedure,
		svc.RespondNonce,
		connect.WithSchema(radioServiceMethods.ByName("RespondNonce")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceCreateSessionHandler := connect.NewUnaryHandler(
		RadioServiceCreateSessionProcedure,
		svc.CreateSession,
		connect.WithSchema(radioServiceMethods.ByName("CreateSession")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceGetSessionHandler := connect.NewUnaryHandler(
		RadioServiceGetSessionProcedure,
		svc.GetSession,
		connect.WithSchema(radioServiceMethods.ByName("GetSession")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceDeleteSessionAuthHandler := connect.NewUnaryHandler(
		RadioServiceDeleteSessionAuthProcedure,
		svc.DeleteSessionAuth,
		connect.WithSchema(radioServiceMethods.ByName("DeleteSessionAuth")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceAddTrackHandler := connect.NewUnaryHandler(
		RadioServiceAddTrackProcedure,
		svc.AddTrack,
		connect.WithSchema(radioServiceMethods.ByName("AddTrack")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceRemoveTrackHandler := connect.NewUnaryHandler(
		RadioServiceRemoveTrackProcedure,
		svc.RemoveTrack,
		connect.WithSchema(radioServiceMethods.ByName("RemoveTrack")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceSkipTrackHandler := connect.NewUnaryHandler(
		RadioServiceSkipTrackProcedure,
		svc.SkipTrack,
		connect.WithSchema(radioServiceMethods.ByName("SkipTrack")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceListQueueHandler := connect.NewUnaryHandler(
		RadioServiceListQueueProcedure,
		svc.ListQueue,
		connect.WithSchema(radioServiceMethods.ByName("ListQueue")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceListSessionsHandler := connect.NewUnaryHandler(
		RadioServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(radioServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceListSessionArchivesHandler := connect.NewUnaryHandler(
		RadioServiceListSessionArchivesProcedure,
		svc.ListSessionArchives,
		connect.WithSchema(radioServiceMethods.ByName("ListSessionArchives")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceGetSessionArchiveHandler := connect.NewUnaryHandler(
		RadioServiceGetSessionArchiveProcedure,
		svc.GetSessionArchive,
		connect.WithSchema(radioServiceMethods.ByName("GetSessionArchive")),
		connect.WithHandlerOptions(opts...),
	)
	radioServiceDeleteSessionArchiveHandler := connect.NewUnaryHandler(
		RadioServiceDeleteSessionArchiveProcedure,
		svc.DeleteSessionArchive,
		connect.WithSchema(radioServiceMethods.ByName("DeleteSessionArchive")),
		connect.WithHandlerOptions(opts...),
	)
	return "/RadioService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RadioServicePingProcedure:
			radioServicePingHandler.ServeHTTP(w, r)
		case RadioServiceRequestNonceProcedure:
			radioServiceRequestNonceHandler.ServeHTTP(w, r)
		case RadioServiceRespondNonceProcedure:
			radioServiceRespondNonceHandler.ServeHTTP(w, r)
		case RadioServiceCreateSessionProcedure:
			radioServiceCreateSessionHandler.ServeHTTP(w, r)
		case RadioServiceGetSessionProcedure:
			radioServiceGetSessionHandler.ServeHTTP(w, r)
		case RadioServiceDeleteSessionAuthProcedure:
			radioServiceDeleteSessionAuthHandler.ServeHTTP(w, r)
		case RadioServiceAddTrackProcedure:
			radioServiceAddTrackHandler.ServeHTTP(w, r)
		case RadioServiceRemoveTrackProcedure:
			radioServiceRemoveTrackHandler.ServeHTTP(w, r)
		case RadioServiceSkipTrackProcedure:
			radioServiceSkipTrackHandler.ServeHTTP(w, r)
		case RadioServiceListQueueProcedure:
			radioServiceListQueueHandler.ServeHTTP(w, r)
		case RadioServiceListSessionsProcedure:
			radioServiceListSessionsHandler.ServeHTTP(w, r)
		case RadioServiceListSessionArchivesProcedure:
			radioServiceListSessionArchivesHandler.ServeHTTP(w, r)
		case RadioServiceGetSessionArchiveProcedure:
			radioServiceGetSessionArchiveHandler.ServeHTTP(w, r)
		case RadioServiceDeleteSessionArchiveProcedure:
			radioServiceDeleteSessionArchiveHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRadioServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRadioServiceHandler struct{}

func (UnimplementedRadioServiceHandler) Ping(context.Context, *connect.Request[proto.PingRequest]) (*connect.Response[proto.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.Ping is not implemented"))
}

func (UnimplementedRadioServiceHandler) RequestNonce(context.Context, *connect.Request[proto.RequestNonceRequest]) (*connect.Response[proto.RequestNonceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.RequestNonce is not implemented"))
}

func (UnimplementedRadioServiceHandler) RespondNonce(context.Context, *connect.Request[proto.RespondNonceRequest]) (*connect.Response[proto.RespondNonceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.RespondNonce is not implemented"))
}

func (UnimplementedRadioServiceHandler) CreateSession(context.Context, *connect.Request[proto.CreateSessionRequest]) (*connect.Response[proto.CreateSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.CreateSession is not implemented"))
}

func (UnimplementedRadioServiceHandler) GetSession(context.Context, *connect.Request[proto.GetSessionRequest]) (*connect.Response[proto.GetSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.GetSession is not implemented"))
}

func (UnimplementedRadioServiceHandler) DeleteSessionAuth(context.Context, *connect.Request[proto.DeleteSessionAuthRequest]) (*connect.Response[proto.DeleteSessionAuthResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.DeleteSessionAuth is not implemented"))
}

func (UnimplementedRadioServiceHandler) AddTrack(context.Context, *connect.Request[proto.AddTrackRequest]) (*connect.Response[proto.AddTrackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.AddTrack is not implemented"))
}

func (UnimplementedRadioServiceHandler) RemoveTrack(context.Context, *connect.Request[proto.RemoveTrackRequest]) (*connect.Response[proto.RemoveTrackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.RemoveTrack is not implemented"))
}

func (UnimplementedRadioServiceHandler) SkipTrack(context.Context, *connect.Request[proto.SkipTrackRequest]) (*connect.Response[proto.SkipTrackResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.SkipTrack is not implemented"))
}

func (UnimplementedRadioServiceHandler) ListQueue(context.Context, *connect.Request[proto.ListQueueRequest]) (*connect.Response[proto.ListQueueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.ListQueue is not implemented"))
}

func (UnimplementedRadioServiceHandler) ListSessions(context.Context, *connect.Request[proto.ListSessionsRequest]) (*connect.Response[proto.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.ListSessions is not implemented"))
}

func (UnimplementedRadioServiceHandler) ListSessionArchives(context.Context, *connect.Request[proto.ListSessionArchivesRequest]) (*connect.Response[proto.ListSessionArchivesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.ListSessionArchives is not implemented"))
}

func (UnimplementedRadioServiceHandler) GetSessionArchive(context.Context, *connect.Request[proto.GetSessionArchiveRequest]) (*connect.Response[proto.GetSessionArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.GetSessionArchive is not implemented"))
}

func (UnimplementedRadioServiceHandler) DeleteSessionArchive(context.Context, *connect.Request[proto.DeleteSessionArchiveRequest]) (*connect.Response[proto.DeleteSessionArchiveResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("RadioService.DeleteSessionArchive is not implemented"))
}
