// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file radio-jockey.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file radio-jockey.proto.
 */
export const file_radio_jockey: GenFile = /*@__PURE__*/
  fileDesc("ChJyYWRpby1qb2NrZXkucHJvdG8iJgoQTGlzdFF1ZXVlUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIiQKEUxpc3RRdWV1ZVJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiJwoRUGF1c2VUcmFja1JlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoBSIlChJQYXVzZVRyYWNrUmVzcG9uc2USDwoHbWVzc2FnZRgBIAEoCSI/ChZBZGRUcmFja1RvUXVldWVSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSEQoJdHJhY2tfdXJsGAIgASgJIioKF0FkZFRyYWNrVG9RdWV1ZVJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiEwoRU3RvcFN0cmVhbVJlcXVlc3QiJQoSU3RvcFN0cmVhbVJlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiDQoLUGluZ1JlcXVlc3QiHwoMUGluZ1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkyNQoMUmFkaW9TZXJ2aWNlEiUKBFBpbmcSDC5QaW5nUmVxdWVzdBoNLlBpbmdSZXNwb25zZSIAQhJaEHNlcnZlci9zcmMvcHJvdG9iBnByb3RvMw");

/**
 * @generated from message ListQueueRequest
 */
export type ListQueueRequest = Message<"ListQueueRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message ListQueueRequest.
 * Use `create(ListQueueRequestSchema)` to create a new message.
 */
export const ListQueueRequestSchema: GenMessage<ListQueueRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 0);

/**
 * @generated from message ListQueueResponse
 */
export type ListQueueResponse = Message<"ListQueueResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message ListQueueResponse.
 * Use `create(ListQueueResponseSchema)` to create a new message.
 */
export const ListQueueResponseSchema: GenMessage<ListQueueResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 1);

/**
 * @generated from message PauseTrackRequest
 */
export type PauseTrackRequest = Message<"PauseTrackRequest"> & {
  /**
   * @generated from field: int32 session_id = 1;
   */
  sessionId: number;
};

/**
 * Describes the message PauseTrackRequest.
 * Use `create(PauseTrackRequestSchema)` to create a new message.
 */
export const PauseTrackRequestSchema: GenMessage<PauseTrackRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 2);

/**
 * @generated from message PauseTrackResponse
 */
export type PauseTrackResponse = Message<"PauseTrackResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message PauseTrackResponse.
 * Use `create(PauseTrackResponseSchema)` to create a new message.
 */
export const PauseTrackResponseSchema: GenMessage<PauseTrackResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 3);

/**
 * @generated from message AddTrackToQueueRequest
 */
export type AddTrackToQueueRequest = Message<"AddTrackToQueueRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string track_url = 2;
   */
  trackUrl: string;
};

/**
 * Describes the message AddTrackToQueueRequest.
 * Use `create(AddTrackToQueueRequestSchema)` to create a new message.
 */
export const AddTrackToQueueRequestSchema: GenMessage<AddTrackToQueueRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 4);

/**
 * @generated from message AddTrackToQueueResponse
 */
export type AddTrackToQueueResponse = Message<"AddTrackToQueueResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message AddTrackToQueueResponse.
 * Use `create(AddTrackToQueueResponseSchema)` to create a new message.
 */
export const AddTrackToQueueResponseSchema: GenMessage<AddTrackToQueueResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 5);

/**
 * @generated from message StopStreamRequest
 */
export type StopStreamRequest = Message<"StopStreamRequest"> & {
};

/**
 * Describes the message StopStreamRequest.
 * Use `create(StopStreamRequestSchema)` to create a new message.
 */
export const StopStreamRequestSchema: GenMessage<StopStreamRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 6);

/**
 * @generated from message StopStreamResponse
 */
export type StopStreamResponse = Message<"StopStreamResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message StopStreamResponse.
 * Use `create(StopStreamResponseSchema)` to create a new message.
 */
export const StopStreamResponseSchema: GenMessage<StopStreamResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 7);

/**
 * @generated from message PingRequest
 */
export type PingRequest = Message<"PingRequest"> & {
};

/**
 * Describes the message PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 8);

/**
 * @generated from message PingResponse
 */
export type PingResponse = Message<"PingResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 9);

/**
 * service definition
 *
 * @generated from service RadioService
 */
export const RadioService: GenService<{
  /**
   * @generated from rpc RadioService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_radio_jockey, 0);

