// @generated by protoc-gen-connect-es v1.7.0 with parameter "target=ts"
// @generated from file radio-jockey.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse } from "./radio-jockey_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * service definition
 *
 * @generated from service RadioService
 */
export const RadioService = {
  typeName: "RadioService",
  methods: {
    /**
     * @generated from rpc RadioService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

