// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file radio-jockey.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file radio-jockey.proto.
 */
export const file_radio_jockey: GenFile = /*@__PURE__*/
  fileDesc("ChJyYWRpby1qb2NrZXkucHJvdG8iDQoLUGluZ1JlcXVlc3QiHwoMUGluZ1Jlc3BvbnNlEg8KB21lc3NhZ2UYASABKAkiKgoUQ3JlYXRlU2Vzc2lvblJlcXVlc3QSEgoKc2Vzc2lvbl9pZBgBIAEoCSIrChVDcmVhdGVTZXNzaW9uUmVzcG9uc2USEgoKc3RyZWFtX3VybBgBIAEoCSInChFHZXRTZXNzaW9uUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIigKEkdldFNlc3Npb25SZXNwb25zZRISCgpzdHJlYW1fdXJsGAEgASgJIioKFERlbGV0ZVNlc3Npb25SZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkiFwoVRGVsZXRlU2Vzc2lvblJlc3BvbnNlIjgKD0FkZFRyYWNrUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJEhEKCXRyYWNrX3VybBgCIAEoCSIpChBBZGRUcmFja1Jlc3BvbnNlEhUKBXRyYWNrGAEgASgLMgYuVHJhY2siNwoSUmVtb3ZlVHJhY2tSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkSDQoFaW5kZXgYAiABKA0iFQoTUmVtb3ZlVHJhY2tSZXNwb25zZSImChBTa2lwVHJhY2tSZXF1ZXN0EhIKCnNlc3Npb25faWQYASABKAkiEwoRU2tpcFRyYWNrUmVzcG9uc2UiJgoQTGlzdFF1ZXVlUmVxdWVzdBISCgpzZXNzaW9uX2lkGAEgASgJIisKEUxpc3RRdWV1ZVJlc3BvbnNlEhYKBnRyYWNrcxgBIAMoCzIGLlRyYWNrImcKBVRyYWNrEgoKAmlkGAEgASgDEg4KBnNvdXJjZRgCIAEoCRIRCglzb3VyY2VfaWQYAyABKAkSDQoFdGl0bGUYBCABKAkSDgoGYXJ0aXN0GAUgASgJEhAKCGR1cmF0aW9uGAYgASgDMs0DCgxSYWRpb1NlcnZpY2USJQoEUGluZxIMLlBpbmdSZXF1ZXN0Gg0uUGluZ1Jlc3BvbnNlIgASQAoNQ3JlYXRlU2Vzc2lvbhIVLkNyZWF0ZVNlc3Npb25SZXF1ZXN0GhYuQ3JlYXRlU2Vzc2lvblJlc3BvbnNlIgASNwoKR2V0U2Vzc2lvbhISLkdldFNlc3Npb25SZXF1ZXN0GhMuR2V0U2Vzc2lvblJlc3BvbnNlIgASQAoNRGVsZXRlU2Vzc2lvbhIVLkRlbGV0ZVNlc3Npb25SZXF1ZXN0GhYuRGVsZXRlU2Vzc2lvblJlc3BvbnNlIgASMQoIQWRkVHJhY2sSEC5BZGRUcmFja1JlcXVlc3QaES5BZGRUcmFja1Jlc3BvbnNlIgASOgoLUmVtb3ZlVHJhY2sSEy5SZW1vdmVUcmFja1JlcXVlc3QaFC5SZW1vdmVUcmFja1Jlc3BvbnNlIgASNAoJU2tpcFRyYWNrEhEuU2tpcFRyYWNrUmVxdWVzdBoSLlNraXBUcmFja1Jlc3BvbnNlIgASNAoJTGlzdFF1ZXVlEhEuTGlzdFF1ZXVlUmVxdWVzdBoSLkxpc3RRdWV1ZVJlc3BvbnNlIgBCEloQc2VydmVyL3NyYy9wcm90b2IGcHJvdG8z");

/**
 * @generated from message PingRequest
 */
export type PingRequest = Message<"PingRequest"> & {
};

/**
 * Describes the message PingRequest.
 * Use `create(PingRequestSchema)` to create a new message.
 */
export const PingRequestSchema: GenMessage<PingRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 0);

/**
 * @generated from message PingResponse
 */
export type PingResponse = Message<"PingResponse"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message PingResponse.
 * Use `create(PingResponseSchema)` to create a new message.
 */
export const PingResponseSchema: GenMessage<PingResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 1);

/**
 * @generated from message CreateSessionRequest
 */
export type CreateSessionRequest = Message<"CreateSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message CreateSessionRequest.
 * Use `create(CreateSessionRequestSchema)` to create a new message.
 */
export const CreateSessionRequestSchema: GenMessage<CreateSessionRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 2);

/**
 * @generated from message CreateSessionResponse
 */
export type CreateSessionResponse = Message<"CreateSessionResponse"> & {
  /**
   * @generated from field: string stream_url = 1;
   */
  streamUrl: string;
};

/**
 * Describes the message CreateSessionResponse.
 * Use `create(CreateSessionResponseSchema)` to create a new message.
 */
export const CreateSessionResponseSchema: GenMessage<CreateSessionResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 3);

/**
 * @generated from message GetSessionRequest
 */
export type GetSessionRequest = Message<"GetSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message GetSessionRequest.
 * Use `create(GetSessionRequestSchema)` to create a new message.
 */
export const GetSessionRequestSchema: GenMessage<GetSessionRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 4);

/**
 * @generated from message GetSessionResponse
 */
export type GetSessionResponse = Message<"GetSessionResponse"> & {
  /**
   * @generated from field: string stream_url = 1;
   */
  streamUrl: string;
};

/**
 * Describes the message GetSessionResponse.
 * Use `create(GetSessionResponseSchema)` to create a new message.
 */
export const GetSessionResponseSchema: GenMessage<GetSessionResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 5);

/**
 * @generated from message DeleteSessionRequest
 */
export type DeleteSessionRequest = Message<"DeleteSessionRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message DeleteSessionRequest.
 * Use `create(DeleteSessionRequestSchema)` to create a new message.
 */
export const DeleteSessionRequestSchema: GenMessage<DeleteSessionRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 6);

/**
 * @generated from message DeleteSessionResponse
 */
export type DeleteSessionResponse = Message<"DeleteSessionResponse"> & {
};

/**
 * Describes the message DeleteSessionResponse.
 * Use `create(DeleteSessionResponseSchema)` to create a new message.
 */
export const DeleteSessionResponseSchema: GenMessage<DeleteSessionResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 7);

/**
 * @generated from message AddTrackRequest
 */
export type AddTrackRequest = Message<"AddTrackRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string track_url = 2;
   */
  trackUrl: string;
};

/**
 * Describes the message AddTrackRequest.
 * Use `create(AddTrackRequestSchema)` to create a new message.
 */
export const AddTrackRequestSchema: GenMessage<AddTrackRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 8);

/**
 * @generated from message AddTrackResponse
 */
export type AddTrackResponse = Message<"AddTrackResponse"> & {
  /**
   * @generated from field: Track track = 1;
   */
  track?: Track | undefined;
};

/**
 * Describes the message AddTrackResponse.
 * Use `create(AddTrackResponseSchema)` to create a new message.
 */
export const AddTrackResponseSchema: GenMessage<AddTrackResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 9);

/**
 * @generated from message RemoveTrackRequest
 */
export type RemoveTrackRequest = Message<"RemoveTrackRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: uint32 index = 2;
   */
  index: number;
};

/**
 * Describes the message RemoveTrackRequest.
 * Use `create(RemoveTrackRequestSchema)` to create a new message.
 */
export const RemoveTrackRequestSchema: GenMessage<RemoveTrackRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 10);

/**
 * @generated from message RemoveTrackResponse
 */
export type RemoveTrackResponse = Message<"RemoveTrackResponse"> & {
};

/**
 * Describes the message RemoveTrackResponse.
 * Use `create(RemoveTrackResponseSchema)` to create a new message.
 */
export const RemoveTrackResponseSchema: GenMessage<RemoveTrackResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 11);

/**
 * @generated from message SkipTrackRequest
 */
export type SkipTrackRequest = Message<"SkipTrackRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message SkipTrackRequest.
 * Use `create(SkipTrackRequestSchema)` to create a new message.
 */
export const SkipTrackRequestSchema: GenMessage<SkipTrackRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 12);

/**
 * @generated from message SkipTrackResponse
 */
export type SkipTrackResponse = Message<"SkipTrackResponse"> & {
};

/**
 * Describes the message SkipTrackResponse.
 * Use `create(SkipTrackResponseSchema)` to create a new message.
 */
export const SkipTrackResponseSchema: GenMessage<SkipTrackResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 13);

/**
 * @generated from message ListQueueRequest
 */
export type ListQueueRequest = Message<"ListQueueRequest"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;
};

/**
 * Describes the message ListQueueRequest.
 * Use `create(ListQueueRequestSchema)` to create a new message.
 */
export const ListQueueRequestSchema: GenMessage<ListQueueRequest> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 14);

/**
 * @generated from message ListQueueResponse
 */
export type ListQueueResponse = Message<"ListQueueResponse"> & {
  /**
   * @generated from field: repeated Track tracks = 1;
   */
  tracks: Track[];
};

/**
 * Describes the message ListQueueResponse.
 * Use `create(ListQueueResponseSchema)` to create a new message.
 */
export const ListQueueResponseSchema: GenMessage<ListQueueResponse> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 15);

/**
 * @generated from message Track
 */
export type Track = Message<"Track"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: string source_id = 3;
   */
  sourceId: string;

  /**
   * @generated from field: string title = 4;
   */
  title: string;

  /**
   * @generated from field: string artist = 5;
   */
  artist: string;

  /**
   * @generated from field: int64 duration = 6;
   */
  duration: bigint;
};

/**
 * Describes the message Track.
 * Use `create(TrackSchema)` to create a new message.
 */
export const TrackSchema: GenMessage<Track> = /*@__PURE__*/
  messageDesc(file_radio_jockey, 16);

/**
 * @generated from service RadioService
 */
export const RadioService: GenService<{
  /**
   * @generated from rpc RadioService.Ping
   */
  ping: {
    methodKind: "unary";
    input: typeof PingRequestSchema;
    output: typeof PingResponseSchema;
  },
  /**
   * @generated from rpc RadioService.CreateSession
   */
  createSession: {
    methodKind: "unary";
    input: typeof CreateSessionRequestSchema;
    output: typeof CreateSessionResponseSchema;
  },
  /**
   * @generated from rpc RadioService.GetSession
   */
  getSession: {
    methodKind: "unary";
    input: typeof GetSessionRequestSchema;
    output: typeof GetSessionResponseSchema;
  },
  /**
   * @generated from rpc RadioService.DeleteSession
   */
  deleteSession: {
    methodKind: "unary";
    input: typeof DeleteSessionRequestSchema;
    output: typeof DeleteSessionResponseSchema;
  },
  /**
   * @generated from rpc RadioService.AddTrack
   */
  addTrack: {
    methodKind: "unary";
    input: typeof AddTrackRequestSchema;
    output: typeof AddTrackResponseSchema;
  },
  /**
   * @generated from rpc RadioService.RemoveTrack
   */
  removeTrack: {
    methodKind: "unary";
    input: typeof RemoveTrackRequestSchema;
    output: typeof RemoveTrackResponseSchema;
  },
  /**
   * @generated from rpc RadioService.SkipTrack
   */
  skipTrack: {
    methodKind: "unary";
    input: typeof SkipTrackRequestSchema;
    output: typeof SkipTrackResponseSchema;
  },
  /**
   * @generated from rpc RadioService.ListQueue
   */
  listQueue: {
    methodKind: "unary";
    input: typeof ListQueueRequestSchema;
    output: typeof ListQueueResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_radio_jockey, 0);

